apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: beyond
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
      protocol: TCP
