apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-beyond-mysql
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-beyond
  local:
    path: /data/k8s/local-pv/beyond/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node1
